feat(import-world): #MX-134 import external world
OPEN-ENT-NG/minetest pull request #22
Opened 2022-05-03 13:02 UTC by c4role

## Changes
New feature to add external world

## Issue ticket number and link
[MEX-134] https://entsupport.gdapublic.fr/browse/MEX-134

Import external world only in webclient. No communication with python server.

2022-05-03 22:32 UTC, JinDouang commented on src/main/resources/public/ts/directives/import-world/import-world.directive.ts
> +        if(this.world) {
indentation `if (...)`

2022-05-03 22:32 UTC, JinDouang commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +        if(body.getValue(Field.ADDRESS) != null) {
indentation if avec une espace

2022-05-13 13:22 UTC, alicedraillardcgi commented on src/main/resources/public/ts/directives/import-world/import-world.directive.ts
> +            created_at: DateUtils.format(moment().startOf('minute'), DateUtils.FORMAT["DAY/MONTH/YEAR-HOUR-MIN"]),
magic string, tu peux créer un date-format.const.ts et tout mettre dedans 
https://github.com/OPEN-ENT-NG/calendar/blob/dev/src/main/resources/public/ts/core/const/date-format.ts

2022-05-13 13:23 UTC, alicedraillardcgi approved these changes

2022-05-13 13:28 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +    @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
Petit question est ce que il faut être juste connecté pour accédé a tout les API ? Par exemple est ce que je peux supprimer n'importe quelle monde a partir du moment où j'ai l'id ?

2022-05-13 13:29 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/security/MinetestManageRight.java
>  package fr.openent.minetest.security;
Le fichier peux être supprimé s'il est vide

2022-05-13 13:34 UTC, c4role commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +    @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
Pour l'instant oui

2022-05-13 13:34 UTC, c4role commented on src/main/java/fr/openent/minetest/security/MinetestManageRight.java
>  package fr.openent.minetest.security;
Je l'ai laissé car on doit mettre en place des droits prochainement mais on a pas encore toutes les infos

2022-05-13 13:39 UTC, c4role commented on src/main/resources/public/ts/directives/import-world/import-world.directive.ts
> +            created_at: DateUtils.format(moment().startOf('minute'), DateUtils.FORMAT["DAY/MONTH/YEAR-HOUR-MIN"]),
C'est déjà le cas ?

2022-05-13 13:41 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +        if(res == null || res.size() != 1) {
Je ne comprend pas le "res.size() != 1". Est ce que ça veux dire que si on a 2 ou plus d'éléments dans res il y a plus de port disponible ?

2022-05-13 13:43 UTC, c4role commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +        if(res == null || res.size() != 1) {
On ne doit avoir qu'un élément car le contrôle est fait lors de la création d'un monde et qu'on ne peut créer qu'un monde à la fois. Donc si on a plus ou moins d'élément dans le tableau ce n'est pas normal.

2022-05-13 14:15 UTC, BastienBenard reviewed
Si tu a le temps est ce que tu peux faire des tests back et front ?

2022-05-13 14:18 UTC, BastienBenard commented
Est ce qu'il y a une doc API ?

2022-05-13 14:19 UTC, c4role commented
> Si tu a le temps est ce que tu peux faire des tests back et front ?

J'ai prévu d'en faire global au projet après avoir terminé les tickets importants car je ne suis pas trop en avance sur le sprint ...

2022-05-13 14:20 UTC, c4role commented
> Est ce qu'il y a une doc API ?

Oui ici https://entconf.gdapublic.fr/display/MINE/Minetest+Webservice+API#MinetestWebserviceAPI-importWorld

2022-05-13 14:22 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +    @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
c'est a dire, ça va être rechangé avant d'être mis en prod ?

2022-05-13 14:24 UTC, alicedraillardcgi commented on src/main/resources/public/ts/directives/import-world/import-world.directive.ts
> +            created_at: DateUtils.format(moment().startOf('minute'), DateUtils.FORMAT["DAY/MONTH/YEAR-HOUR-MIN"]),
Ah oui j'avais mal lu !

2022-05-13 14:25 UTC, c4role commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +    @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
Non c'est à dire qu'on attend de savoir quel type de droit on va mettre en place et que pour le moment on a juste mis un droit d'authentification pour commencer

2022-05-13 14:26 UTC, BastienBenard commented
> Oui ici https://entconf.gdapublic.fr/display/MINE/Minetest+Webservice+API#MinetestWebserviceAPI-importWorld

Merci j'ai mis le lien dans la description de la PR

2022-05-13 14:30 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +        if(res == null || res.size() != 1) {
D'accord, dans ce cas il ne faut pas changé le message d'erreur ? Pour qu'il soit plus parlant ?

2022-05-13 14:37 UTC, c4role commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +        if(res == null || res.size() != 1) {
Effectivement je peux le rendre plus explicite

2022-05-13 14:39 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +        RequestUtils.bodyToJson(request, pathPrefix + Field.IMPORT_WORLD, body
On ne vérifie pas la présence d'un id dans le body. Il y a pas de risque de null pointer ?

2022-05-13 14:52 UTC, flmartineau commented on src/main/java/fr/openent/minetest/service/impl/DefaultMinetestService.java
> +        String message = String.format("[Minetest@%s::%s]: An error has occurred " + "through python server: %s",
T'es plus obligée de faire un concaténation du coup ^^

2022-05-13 14:53 UTC, c4role commented on src/main/java/fr/openent/minetest/service/impl/DefaultMinetestService.java
> +        String message = String.format("[Minetest@%s::%s]: An error has occurred " + "through python server: %s",
C'est corrigé mais dans la PR suivante !

2022-05-13 15:29 UTC, JinDouang commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +        RequestUtils.bodyToJson(request, pathPrefix + Field.IMPORT_WORLD, body
/worlds/import/:id

2022-05-13 15:30 UTC, JinDouang commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +    @Delete("/worlds/import")
/worlds/import/:worldId

2022-05-25 06:30 UTC, flmartineau commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +                String message = String.format("[Minetest@%s::deleteWorld]: An error has occurred while deleting import world: %s",
`[Minetest@%s::deleteImportWorld]` plutôt non ?

2022-05-25 06:39 UTC, flmartineau commented on src/test/java/fr/openent/minetest/services/DefaultWorldServiceTest.java
> +        JsonObject expectedWorld = new JsonObject()
A quoi ça te sert de réécrire le même objet à la main ? ^^

2022-05-25 06:59 UTC, JinDouang requested changes

2022-05-25 06:59 UTC, JinDouang commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +    @Put("/worlds/:id")
Dans ton confluence, il n'est pas à jour : https://entconf.gdapublic.fr/pages/viewpage.action?spaceKey=MINE&title=Minetest+Webservice+API#MinetestWebserviceAPI-updateWorld

Ici tu les renseignes l'id (en mode REST) mais ce n'est pas maj dans ta doc

2022-05-25 06:59 UTC, JinDouang commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +    @Put("/worlds/import/:id")
Dans ton confluence, il n'est pas à jour : https://entconf.gdapublic.fr/pages/viewpage.action?spaceKey=MINE&title=Minetest+Webservice+API#MinetestWebserviceAPI-updateImportWorld

Ici tu les renseignes l'id (en mode REST) mais ce n'est pas maj dans ta doc

2022-05-25 06:59 UTC, JinDouang commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +        RequestUtils.bodyToJson(request, pathPrefix + Field.IMPORT_WORLD, body
Du coup ton id est toujours dans ton payload ?
Tu n'as pas l'air de le récupérer via request.params("id")

2022-05-25 06:59 UTC, JinDouang commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +    @Put("/worlds/status/:id")
Je ne vois pas l'API concernant la maj de status dans ton confluence Du coup ton id est toujours dans ton payload ?
Tu n'as pas l'air de le récupérer via request.params("id") 😅

2022-05-25 06:59 UTC, JinDouang commented on src/main/java/fr/openent/minetest/controller/MinetestController.java
> +        if (!request.params().contains(Field.ID)) {
Du coup t'aurais plus besoin de le faire si tu renseignes l'id directement (comme tu as fait pour ton PUT)

2022-05-25 06:59 UTC, JinDouang commented on src/main/resources/public/ts/services/__test__/minetest.service.test.ts
> +            expect(response.config.url).toEqual(`/minetest/worlds/import?id=${world._id}`);
Du coup pour ton endpoint tu ne fais pas en REST ?

dommage comme tu as fait la même chose pour le PUT en mettant l'id...

2022-05-25 06:59 UTC, JinDouang commented on src/test/java/fr/openent/minetest/services/DefaultWorldServiceTest.java
> +        JsonObject expectedWorld = new JsonObject()
Dans les expects on veut rendre notre objet "visible"

tu l'as construits c'est bien mais on aimerait qu'il soit comme ça plutôt : 

`String expectedWorld = "{\"_id\":\"5fzef5\",\"owner_id\":\"ownerId\",\"owner_name\":\"ownerName\",\"owner_login\":\"ownerLogin\",\"created_at\":\"createdAt\",\"updated_at\":\"updatedAt\",\"title\":\"my world\",\"address\":\"myworld.fr\",\"port\":\"30000\",\"isExternal\":true}"`

de cette manière tu pourras vérifier le payload que le mongo t'enverra en mode `toString()` (à rectifier dans ton assert du coup)

exemple : https://github.com/OPEN-ENT-NG/lool-connector/commit/07a57349e47dd1483e7b6fad2e5628786b8ca82e#diff-7440c835c4e389f78c388d4087c2f38a9ede693348e96c8d737db60ea11ff0d6R56

2022-05-25 06:59 UTC, JinDouang commented on src/test/java/fr/openent/minetest/services/DefaultWorldServiceTest.java
> +        JsonObject expectedQuery = new JsonObject()
cf commentaire au dessus avec l'exemple

2022-05-26 09:33 UTC, JinDouang approved these changes

2022-05-30 06:57 UTC, merged