MEX-148 Update password
OPEN-ENT-NG/minetest pull request #25
Opened 2022-05-31 13:57 UTC by c4role

## Describe your changes

You now can update password

https://entconf.gdapublic.fr/display/MINE/Minetest+Webservice+API

## Checklist tests
Create world, go on minetest and connect to this world. Quit the map, update password and try again to enter in the world with old password. This should not be OK, and then try to enter in the map with the new password you juste defined.

## Issue ticket number and link
[MEX-148] https://entsupport.gdapublic.fr/browse/MEX-148

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-05-31 14:15 UTC, JinDouang commented
@c4role Tu as changé/rajouté une dépendance dans le projet ? Je ne le vois pas dans tes files changed

2022-05-31 14:17 UTC, BastienBenard approved these changes
Il manque juste les tests pour DefaultWorldService.java

2022-05-31 14:20 UTC, c4role commented
> Il manque juste les tests pour DefaultWorldService.java

oui, j'ai expliqué pourquoi sur slack :)

2022-05-31 14:24 UTC, JinDouang requested changes

2022-05-31 14:24 UTC, JinDouang commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +        if(body.getValue(Field.PASSWORD) != null) {
On sait quel est le type de "password" ? Si possible il faudrait spécifier son type car tu utilises getValue ce qui fait qu'on ne sait pas vraiment sa nature

2022-05-31 14:24 UTC, JinDouang commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +            resetPassword(String.valueOf(body.getValue(Field.PASSWORD)), body);
Si je comprends bien, à chaque fois que tu ajoutes dans ton payload (via le front) le password, avant de faire un update dans le mongo tu appelles la méthode resetPassword qui va se contenter d'appeler ton server pour faire l'interaction sans vérifier son retour ?

Qu'est-ce qu'il se passe si jamais ton mongo fail son update mais que l'appel se 'resetPassword' se fait quand même (puisqu'il est appelé juste avant le mongo) sans vérifier son retour ?

2022-05-31 14:24 UTC, JinDouang commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +        minetestService.action(body, MinestestServiceAction.RESET_PASSWORD)
On connait le retour de l'API de reset password ?

Ce retour est bien à jour dessus : https://entconf.gdapublic.fr/display/MINE/Minetest+Service+API#MinetestServiceAPI-resetPassword ?
@sjollois

2022-05-31 14:31 UTC, flmartineau commented on src/main/java/fr/openent/minetest/service/impl/DefaultWorldService.java
> +            worldData.put(Field.TITLE, body.getValue(Field.TITLE));
Au lieu d'utiliser des `body.getValue`, tu peux pas faire des `getString`, `getInteger`, etc.. ? Tu connais pas le type ?

2022-06-01 07:45 UTC, JinDouang commented on src/main/resources/i18n/fr.json
> +  "minetest.reset.password": "Réinitialiser le mot de passe",
fais pareil pour en.json!

2022-06-02 09:57 UTC, JinDouang approved these changes

2022-06-02 09:59 UTC, merged