Mex 137
OPEN-ENT-NG/minetest pull request #37
Opened 2022-08-11 14:07 UTC by sjollois

## Describe your changes
Feature to close the worlds automaticaly. The user has the choice to disable this automatic closing. (enable by default)

## Checklist tests
Create a world. enable or disable the automatic close. open the world. wait that the cron pass. check if the world has been close.

## Issue ticket number and link
[https://jira.support-ent.fr/browse/MEX-137](url)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-12 07:42 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/Minetest.java
> +			new CronTrigger(vertx, config.getString("shutting-down-cron")).schedule(
Magic String

2022-08-12 07:49 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +    private void updateNextWorld(int index, JsonArray worlds, Handler<Either<String, JsonObject>> result) {
Pourquoi ne pas utilise des futures a la palce des handler ? Ce permettrais de faire un compose ligne 61

2022-08-12 07:59 UTC, BastienBenard commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +                Thread.sleep(500);
Juste pour savoir pourquoi faire un sleep.

2022-08-12 08:10 UTC, BastienBenard commented on src/main/resources/public/sass/global/components/_switch.scss
> +switch {
ça ne rique pas d'impacter le scss des autres modules ? Si ce n'est que pour minetest peut être mettre ce scss dans un body.minetest {}

2022-08-12 08:12 UTC, BastienBenard commented on src/main/resources/public/ts/directives/properties-world/properties-world.directive.ts
> +        if(this.world.shuttingDown == undefined){
indentation

2022-08-12 09:08 UTC, sjollois commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +    private void updateNextWorld(int index, JsonArray worlds, Handler<Either<String, JsonObject>> result) {
c'est une fonction récursive, cela reste plus simple en handler

2022-08-12 09:11 UTC, sjollois commented on src/main/resources/public/sass/global/components/_switch.scss
> +switch {
dans le scc de _minetest.scss, on a ce code :
`body.minetest {
  @import "components/index";
}`
donc pas de risque

2022-08-16 10:26 UTC, JinDouang commented
attention au typo de ton commit : feat(shutting-down-cron): #MX-137 close automaticaly worlds if enable => feat(shutting-down-cron): #MEX-137 close automaticaly worlds if enable (il manquait le E )

2022-08-16 13:04 UTC, JinDouang requested changes

2022-08-16 13:04 UTC, JinDouang commented on src/main/java/fr/openent/minetest/Minetest.java
> +			log.fatal("Invalid shutting-down-cron cron expression.", e);
```suggestion
			log.fatal("Invalid shutting-down-cron cron expression + " e.getMessage());
```

2022-08-16 13:04 UTC, JinDouang commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +    public void handle(Long event) {
Au niveau des logs infos, tu devrais mettre des mots-clés qui concerneraient minetest

2022-08-16 13:04 UTC, JinDouang commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +                });
```suggestion
        log.info("[" + this.getClass().getSimpleName() + "] shutting down world launched");
        worldService.getMongo(null, null, null, null, null, null,
                        true, true, new JsonObject())
                .compose(this::updateStatusAllWorld)
                .onSuccess(res -> log.info("[" + this.getClass().getSimpleName() + "] shutting down cron finish successfully"))
                .onFailure(err -> log.error("[" + this.getClass().getSimpleName() + "] " +
                        "shutting down cron on failure: " + err.getMessage()));
```

Exemple de log + indentation

2022-08-16 13:04 UTC, JinDouang commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +        if(res.isEmpty()){
Indentation

2022-08-16 13:04 UTC, JinDouang commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +}
Voici ma proposition : 
```suggestion
      private Future<Void> updateStatusAllWorld(JsonArray worlds) {
        Promise<Void> promise = Promise.promise();

        if (worlds.isEmpty()) {
            promise.complete();
        } else {
            Future<JsonObject> current = Future.succeededFuture();

            for (int i = 0; i < worlds.size(); i++) {
                int finalI = i;
                current = current.compose(v -> shutDownWorld(worlds.getJsonObject(finalI)).onComplete(Future.succeededFuture()));
            }
            current
                    .onSuccess(res -> promise.complete())
                    .onFailure(err -> {
                        err.printStackTrace();
                        promise.fail(err.getMessage());
                    });   
        }
        return promise.future();
    }

    private Future<JsonObject> shutDownWorld(JsonObject world) {
        Promise<JsonObject> promise = Promise.promise();
        vertx.setTimer(500, timer ->
                worldService.updateStatus(world)
                        .onSuccess(promise::complete)
                        .onFailure(err -> {
                            log.error("[Minetest@recursiveShuttingDownWorld] Failed to update status of the world in cron : " + world + err.getMessage());
                            err.printStackTrace();
                            promise.fail(err.getMessage());
                        }));

        return promise.future();
    }    
```

2022-08-16 13:04 UTC, JinDouang commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +}
On utilise les futures au lieu de faire une méthode récursive ou thread.sleep en utilisant vertx timer et en faisant un traitement sequentiel

2022-08-18 08:20 UTC, JinDouang requested changes

2022-08-18 08:20 UTC, JinDouang commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +                    log.error("[Minetest@ShuttingDownWorld] Shutting down cron on failure", err);
```suggestion
                  log.error("[Minetest@ShuttingDownWorld] Shutting down cron on failure: " + err.getMessage());
                    err.printStackTrace();
```

2022-08-18 08:20 UTC, JinDouang commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +                    log.error("[Minetest@ShuttingDownWorld] Shutting down cron on failure", err);
Voici ma suggestion pour mieux comprendre les erreurs dessus

2022-08-18 08:20 UTC, JinDouang commented on src/main/java/fr/openent/minetest/cron/ShuttingDownWorld.java
> +        vertx.setTimer(500, timer ->
Hum je te conseil d'utiliser une constant "TIMER"

Dans les déclarations de ta classe :
`
    private final long TIMER = 500;

`

et du coup ça ferait : 
```suggestion
        vertx.setTimer(TIMER, timer ->
```

2022-08-18 08:37 UTC, JinDouang approved these changes

2022-08-18 08:38 UTC, merged