feat(search): #MEX-64 search bar in front
OPEN-ENT-NG/minetest pull request #38
Opened 2022-08-11 16:13 UTC by sjollois

## Describe your changes
Add search bar in front to search by title or owner name 
## Checklist tests
search specific world by title and then by author
## Issue ticket number and link
[https://jira.support-ent.fr/browse/MEX-64](url)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-12 12:29 UTC, qperie approved these changes

2022-08-16 10:25 UTC, JinDouang requested changes

2022-08-16 10:25 UTC, JinDouang commented on src/main/resources/public/ts/controllers/minetest.controller.ts
> +    filterWorlds(searching: string): any;
typage

2022-08-16 10:25 UTC, JinDouang commented on src/main/resources/public/ts/controllers/minetest.controller.ts
> +    filterWorlds(searching:string): any {
typage (World[])

2022-08-16 10:25 UTC, JinDouang commented on src/main/resources/public/ts/controllers/minetest.controller.ts
> +        if(!!searching){
juste if (searching) ce n'est pas suffisant ?

2022-08-16 10:25 UTC, JinDouang commented on src/main/resources/public/ts/controllers/minetest.controller.ts
> +            });
```suggestion
          return _.filter(this.worlds.all, (world) => 
                world.owner_name.toLowerCase().includes(searching.toLowerCase()) || 
                world.title.toLowerCase().includes(searching.toLowerCase())
            );
```

2022-08-16 14:39 UTC, JinDouang approved these changes

2022-08-16 15:18 UTC, merged