feat(loader): #MEX-199 add loader when getting minetest worlds
OPEN-ENT-NG/minetest pull request #45
Opened 2022-09-14 09:13 UTC by sjollois

## Describe your changes
add loader when getting minetest worlds
## Checklist tests
go to minetest first page
## Issue ticket number and link
[https://jira.support-ent.fr/browse/MEX-199](url)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [x] If it is a consequent feature, I have added thorough tests.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-14 13:04 UTC, qperie approved these changes

2022-09-14 16:48 UTC, JinDouang requested changes

2022-09-14 16:48 UTC, JinDouang commented on src/main/resources/public/ts/directives/loader/loader.directive.ts
> +export const LoaderDirective = ng.directive('loader', () => {
Essaye de faire avec les classes

2022-09-15 10:25 UTC, JinDouang approved these changes

2022-09-15 11:30 UTC, merged